version: '3.8'
services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./:/home/bot/app:cached
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
