import discord
from discord import app_commands
from discord.ext import commands
import asyncio
import io
import json
import os

# --- CONFIGURATION ---
TRANSCRIPT_CHANNEL_ID = 1503380993023803623
BANNER_URL = "https://cdn.discordapp.com/attachments/1503380982831513701/1503418351081226250/b4ce5269-498b-41d1-8c2e-b1b02eef76e5.png?ex=6a0346f3&is=6a01f573&hm=5b5cc9925f7f0cb856411f23f7fe46556431f6655ad3aea71023e79a78c59ecf"
TICKET_IMAGE_URL = "https://cdn.discordapp.com/attachments/1340943454934667345/1340943454934667345/image_449024.jpg"
SETTINGS_FILE = "ticket_settings.json"


def load_settings():
    if os.path.exists(SETTINGS_FILE):
        with open(SETTINGS_FILE, "r") as f:
            return json.load(f)
    return {}


def save_settings(data):
    with open(SETTINGS_FILE, "w") as f:
        json.dump(data, f, indent=4)


class TicketControls(discord.ui.View):
    def __init__(self):
        super().__init__(timeout=None)

    @discord.ui.button(label="Claim Ticket", style=discord.ButtonStyle.success, emoji="🙋‍♂️", custom_id="persistent:claim")
    async def claim(self, interaction: discord.Interaction, button: discord.ui.Button):
        if button.disabled:
            return await interaction.response.send_message("⚠️ This ticket has already been claimed.", ephemeral=True)

        button.disabled = True
        button.label = f"Claimed by {interaction.user.name}"
        button.style = discord.ButtonStyle.secondary

        embed = discord.Embed(
            description=f"✨ **Staff Assigned:** {interaction.user.mention} is now handling your request.",
            color=discord.Color.purple()
        )
        await interaction.response.edit_message(view=self)
        await interaction.followup.send(embed=embed)

    @discord.ui.button(label="Transcript", style=discord.ButtonStyle.secondary, emoji="📑", custom_id="persistent:transcript")
    async def transcript(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.defer(ephemeral=True)

        try:
            await interaction.edit_original_response(content="💾 **Generating Transcript...**")

            content = "GLADBYTE SUPPORT TRANSCRIPT\n━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            async for message in interaction.channel.history(limit=None, oldest_first=True):
                time = message.created_at.strftime("%Y-%m-%d %H:%M")
                content += f"[{time}] {message.author}: {message.content}\n"
                if message.attachments:
                    for att in message.attachments:
                        content += f"📎 Attachment: {att.url}\n"

            file = discord.File(io.BytesIO(content.encode()), filename=f"transcript-{interaction.channel.name}.txt")
            log_channel = interaction.guild.get_channel(TRANSCRIPT_CHANNEL_ID)

            if log_channel:
                transcript_embed = discord.Embed(
                    title="📑 New Transcript",
                    description=f"**Channel:** `{interaction.channel.name}`\n**Generated by:** {interaction.user.mention}",
                    color=discord.Color.purple()
                )
                await log_channel.send(embed=transcript_embed, file=file)
                await interaction.edit_original_response(content="✅ **Transcript archived in staff logs.**")
            else:
                await interaction.edit_original_response(content="⚠️ **Transcript channel not found. Check TRANSCRIPT_CHANNEL_ID.**")
        except Exception as e:
            await interaction.edit_original_response(content=f"❌ **Error:** {e}")

    @discord.ui.button(label="Close Ticket", style=discord.ButtonStyle.danger, emoji="🔒", custom_id="persistent:close")
    async def close(self, interaction: discord.Interaction, button: discord.ui.Button):
        channel = interaction.channel
        await interaction.response.send_message("🔒 **Closing ticket in 5 seconds...**")
        
        for i in range(5, 0, -1):
            await asyncio.sleep(1)
            try:
                await channel.send(f"⏳ **Closing in {i}s...**")
            except:
                pass

        await channel.delete()


class GladbyteDropdown(discord.ui.Select):
    def __init__(self, category_id: int = None):
        self.category_id = category_id
        options = [
            discord.SelectOption(label="General Support", emoji="🛰️", description="General questions & server assistance"),
            discord.SelectOption(label="Minecraft Support", emoji="🎮", description="Gameplay, bugs & plugin help"),
            discord.SelectOption(label="VPS Purchase", emoji="⚡", description="Virtual Private Servers & pricing"),
            discord.SelectOption(label="Minecraft Server Purchase", emoji="🕹️", description="High-Frequency CPU Minecraft Hosting"),
            discord.SelectOption(label="Partnership Support", emoji="🤝", description="Collaborations & proposals"),
            discord.SelectOption(label="Any Other", emoji="🛠️", description="Other queries & support"),
        ]
        super().__init__(placeholder="📥 Select a Department...", custom_id="persistent:dropdown", options=options)

    async def callback(self, interaction: discord.Interaction):
        await interaction.response.defer(ephemeral=True)

        guild = interaction.guild
        category = None

        if self.category_id:
            category = guild.get_channel(self.category_id)

        if category is None and interaction.channel:
            try:
                category = interaction.channel.category
            except:
                pass

        if category is None:
            settings = load_settings()
            cat_id = settings.get(str(guild.id))
            if cat_id:
                category = guild.get_channel(cat_id)

        if category is None:
            return await interaction.followup.send(
                "❌ **Could not find a valid category. Please re-run `/setup`.**",
                ephemeral=True
            )

        try:
            ticket_channel = await guild.create_text_channel(
                name=f"🎫-{self.values[0].lower().replace(' ', '-')}-{interaction.user.name}",
                category=category
            )

            await ticket_channel.set_permissions(guild.default_role, read_messages=False)
            await ticket_channel.set_permissions(
                interaction.user,
                read_messages=True,
                send_messages=True,
                attach_files=True,
                embed_links=True
            )
            await ticket_channel.set_permissions(
                guild.me,
                read_messages=True,
                send_messages=True,
                manage_channels=True,
                manage_messages=True
            )

            await interaction.followup.send(f"✅ **Ticket Created!** {ticket_channel.mention}", ephemeral=True)

            boot = await ticket_channel.send("⚡ **System Booting...**")
            await asyncio.sleep(0.7)
            await boot.edit(content="🛰️ **Connecting to Gladbyte Uplink...**")
            await asyncio.sleep(0.5)
            await boot.edit(content="📡 **Establishing Secure Channel...**")
            await asyncio.sleep(0.5)
            await boot.delete()

            opened = discord.Embed(
                title="✅ Ticket Opened",
                description=f"📬 **{interaction.user.mention}** — your **{self.values[0]}** ticket has been created!",
                color=discord.Color.green()
            )
            await ticket_channel.send(embed=opened)

            panel_embed = discord.Embed(
                title="🏢 Gladbyte Helpdesk",
                description=(
                    f"👋 **Hello {interaction.user.mention}!**\n\n"
                    f"Thank you for contacting **Gladbyte Limited**.\n"
                    f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                    f"🛠️ **Department:** {self.values[0]}\n"
                    f"📝 **Please describe your request in detail below.**\n\n"
                    f"💡 *A staff member will be with you shortly.*"
                ),
                color=discord.Color.purple()
            )
            panel_embed.set_thumbnail(url=TICKET_IMAGE_URL)
            if guild.icon:
                panel_embed.set_footer(
                    text="Gladbyte Limited • Reliable Cloud Solutions",
                    icon_url=guild.icon.url
                )

            await ticket_channel.send(embed=panel_embed, view=TicketControls())

        except discord.Forbidden:
            await interaction.followup.send(
                "❌ **Bot missing permissions!** I need: `Manage Channels`, `Manage Messages`, and `Manage Roles`.",
                ephemeral=True
            )
        except Exception as e:
            await interaction.followup.send(f"❌ **Error creating ticket:** {e}", ephemeral=True)


class GladbyteView(discord.ui.View):
    def __init__(self, category_id: int = None):
        super().__init__(timeout=None)
        self.add_item(GladbyteDropdown(category_id))


class GladbyteTickets(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(name="setup", description="🚀 Deploy Ticket System (Admin Only)")
    @app_commands.checks.has_permissions(administrator=True)
    async def glad_setup(self, interaction: discord.Interaction, channel: discord.TextChannel, category: discord.CategoryChannel):
        await interaction.response.send_message("📡 **Syncing UI...**", ephemeral=True)

        settings = load_settings()
        settings[str(interaction.guild.id)] = category.id
        save_settings(settings)
        print(f"📝 Saved category {category.id} for guild {interaction.guild.id}")

        embed = discord.Embed(
            title="🏢 ━━━ GLADBYTE HELPDESK ━━━ 🏢",
            description=(
                "━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "🛰️ **General Support**\n"
                "For general questions or server-related assistance.\n"
                "Our support team will help you promptly.\n\n"
                "🎮 **Minecraft Support**\n"
                "Help with gameplay issues, bugs, or plugins.\n"
                "Please share clear details for faster support.\n\n"
                "⚡ **VPS Purchase**\n"
                "Know about our Virtual Private Servers\n"
                "and buying Cheap / Budget and More VPS.\n\n"
                "🕹️ **Minecraft Server Purchase**\n"
                "Create a Ticket here to Purchase\n"
                "High-Frequency CPUs Minecraft Servers.\n\n"
                "🤝 **Partnership Support**\n"
                "Questions about partnerships or collaborations.\n"
                "Share your proposal or details for review.\n\n"
                "🛠️ **Any Other**\n"
                "Create a Ticket Under this Category for Any Other\n"
                "Query or Support by our Team Members.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━"
            ),
            color=discord.Color.purple()
        )
        embed.set_image(url=BANNER_URL)
        embed.set_footer(text="Ender Bot • Reliable Cloud Solutions")

        await channel.send(embed=embed, view=GladbyteView(category.id))
        await interaction.edit_original_response(content="✅ **Helpdesk is live.**")


async def setup(bot):
    await bot.add_cog(GladbyteTickets(bot))